ci:
  skip: [pytest]

default_language_version:
  python: python3.12

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        args: [--max-line-length=100]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
    -   id: mypy
        additional_dependencies: [types-pyyaml]
        exclude: ^testing/resources/
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks:
    - id: ruff
      types_or: [ python, pyi ]
      args: [ --fix ]
      select: [
      "E",
      "F",
      "UP",
      "B",
      "SIM",
      "I",
      "TCH",
      "D",
      "ARG",
      ]
    - id: ruff-format
      types_or: [ python, pyi ]
